default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: calendar_development

test:
  <<: *default
  database: calendar_test

production:
  <<: *default
  database: calendar_production
  username: dbtest
  password: <%= ENV['DBTEST_DATABASE_PASSWORD'] %>
