default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host: localhost
  pool: 5

development:
  <<: *default
  database: calendar_development

test:
  <<: *default
  database: calendar_test

production:
  <<: *default
  database: calendar_production