# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 486be0c870ac9ceaf1173c297e473771efb7e53279334b14936c35ffca74d160f5057fb05ead17e33e52a6141cdb5116ff514622d6f9a98e3165c128d91dd3aa

test:
  secret_key_base: b01616cd0387901803dfb07b69b0ace06b6e34ae8a06839f327e3342fee0ab4eaa315038d178f5bcf30287c50e38b6cb1c435e784665246ad68df8077672c0fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
